### ISSUE TITLE
First!

### ISSUE THREAD

**Issue by hilburn** [CorvusUrro/PrSrd#1]
While you are free to use the asm code I wrote for SSTOW with their permission - the library classes I added to make it work are covered separately, so if you want to include it you'd have to ask me and/or @way2muchnoise

**Comment by SgtPunishment** [comment]
@CorvusUrro you really need to respond to @hilburn

**Comment by hilburn** [comment]
Simply for the 9 days it took you to half-heartedly "ask [me] whatever it is [you] need to ask": Denied
